Feature/61 configuration validation
cloudant-labs/kafka-connect-cloudant pull request #70
Opened 2022-04-05 09:57 UTC by tomblench

* Feature PR for enhanced configuration and validation *

- Breaking changes to sink and source options (see README and CHANGELOG)
- Support for all auth methods

See #61, #67, #68

2022-04-06 16:15 UTC, ricellis requested changes
A few suggestions, but on the whole I think this is good.

2022-04-12 07:53 UTC, tomblench commented on README.md
> +cloudant.password|\<your-password\>|NO|None|The Cloudant password to use for authentication (when using `couchdb_session` or `basic` authentication).
See updated README with dedicated section for auth options

2022-04-12 07:55 UTC, tomblench commented on src/main/java/com/ibm/cloudant/kafka/connect/CloudantConnectorConfig.java
> +    }
Done - for now all at `Importance.HIGH` and in `DATABASE_GROUP` - not sure if that's right but I don't think it's a blocker

2022-04-12 07:56 UTC, tomblench commented on src/main/java/com/ibm/cloudant/kafka/connect/ListRecommender.java
> +            throw new ConfigException(key, value, "Value must be one of: " + this.validValues);
Done - added to `MessageKey` and `messages_en_US.properties`

2022-04-12 07:57 UTC, tomblench commented on src/main/java/com/ibm/cloudant/kafka/connect/UrlValidator.java
> +        throw new ConfigException(name, value, "Value not a URL: " + value);
Done

2022-04-12 13:50 UTC, ricellis commented on README.md
> +cloudant.url|https://\<your-account\>.cloudant.com|YES|None|The Cloudant server to read documents from.
You missed this in the table, but did add it in the example block so I'm fine, a URL is a URL 😄

2022-04-12 13:50 UTC, ricellis commented on src/main/java/com/ibm/cloudant/kafka/connect/CloudantConnectorConfig.java
> +    }
Agree I honestly find the H, M, L importance a bit hard to fathom, it really depends on the requirements. Clearly some properties are of very high importance, but only when using specific auth types or features. I think going with this for now is OK.

2022-04-12 14:14 UTC, ricellis approved these changes

2022-04-12 15:15 UTC, emlaver approved these changes

2022-04-12 15:41 UTC, merged